version: '3.8'

services:
  fin:
    container_name: fin_service
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      fin_db:
        condition: service_healthy
    networks:
      - fin_network
    restart: always

  fin_db:
    container_name: fin_service_db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fin_network
    restart: always

networks:
  fin_network:
    driver: bridge

volumes:
  postgres_data: 